service: lambda-scraper
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 35 # default = 6, apigateway max = 29
  deploymentBucket:
    name: sls-state

functions:
  api:
    handler: handler.api
    environment:
      GIT_TOKEN: ${env:GIT_TOKEN}
      BUILD_ID: ${env:BUILD_ID}
      STAGE: ${env:STAGE}
    events:
      - http: any /api/{id}