service: lambda-scraper
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 30 # default = 6, apigateway max = 30
  deploymentBucket:
    name: sls-state

functions:
  api:
    handler: handler.api
    environment:
      GIT_TOKEN: ${env:GIT_TOKEN}
      BUILD_ID: ${env:BUILD_ID}
      STAGE: ${env:STAGE}
      PG_URI: ${env:PG_URI}
      KEY: ${env:KEY}
    events:
      - http: any /api/{id}